import type { TagInput } from "../tag/type.js";

export interface RawFeedItem {
  title?: string;
  description?: string;
  content?: string;
  summary?: string;
  contentSnippet?: string;

  link?: string;
  guid?: string;

  isoDate?: string;
  pubDate?: string;

  author?: string | null;

  creator?: string;

  categories?: string[];

  enclosure?: {
    url?: string;
  };

  image?: {
    url?: string;
  };

  media?: {
    thumbnail?: {
      url?: string;
    };
  };

  [key: string]: unknown;
}

export interface NormalizedArticle {
  sourceId: string;

  //channelUrl?: string;

  categorySlug: string;

  title: string;

  slug: string;

  description?: string;

  content?: string;

  url: string;

  imageUrl?: string | null;

  author?: string;

  publishedAt: Date;

  status?: "DRAFT" | "PUBLISHED" | "ARCHIVED"; // maps to $Enums.ArticleStatus

  language?: string; // from Source.language

  contentHash?: string; // generated by DeduplicatorService.generateContentHash

  // optional normalized extras
  tags?: TagInput[]; // flatten ArticleTag relation
  entities?: {
    people?: string[];
    companies?: string[];
    organizations?: string[];
    countries?: string[];
    cities?: string[];
    technologies?: string[];
    products?: string[];
    events?: string[];
    stocks?: string[];
  };
  analysisId?: string | null; // if you want to reference analysis
}


/** RSS.service */
export interface FeedResult {
  url: string;
  data?: string;
  error?: string;
}

export interface RawArticle {
  sourceId: string;
  sourceUrl: string;
  language?: string;
  metadata?: unknown;
  raw: unknown;
}

export interface SourceConfig {
  sourceId: string;
  url: string;
  language: string;
}

export interface ParsedFeed {
  metadata: {
    title?: string;
    description?: string;
    link?: string;
    language?: string;
    lastBuildDate?: string;
  };
  items: any[];
}